import React from "react";
import type {Metadata} from "next";
import "./globals.css";
import {LayoutGrid} from "@/components/layout/layout-grid";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`antialiased`}>
    <LayoutGrid>
      {children}
    </LayoutGrid>
    </body>
    </html>
  );
}
